INSERT INTO users (full_name, email, password_hash, role, is_active)
VALUES
    ('Ivan Petrenko', 'ivan@example.com', '$2a$10$8C6z10WTmWTFcVrJ4fanmO105xgexLMMazyjTKEwzw7yBkZYbulDS', 'USER', TRUE),
    ('Olena Shevchenko', 'olena.shevchenko@example.com', '$2a$10$8C6z10WTmWTFcVrJ4fanmO105xgexLMMazyjTKEwzw7yBkZYbulDS', 'USER', TRUE),
    ('Serhii Technician', 'serhii.tech@example.com', '$2a$10$8C6z10WTmWTFcVrJ4fanmO105xgexLMMazyjTKEwzw7yBkZYbulDS', 'TECHNICIAN', TRUE),
    ('Svitlana Melnyk', 'svitlana.melnyk@example.com', '$2a$10$8C6z10WTmWTFcVrJ4fanmO105xgexLMMazyjTKEwzw7yBkZYbulDS', 'TECHNICIAN', TRUE);

INSERT INTO repair_requests (
    user_id,
    technician_id,
    equipment_type,
    equipment_name,
    title,
    problem_description,
    user_comment,
    technician_comment,
    repair_result,
    status,
    priority,
    created_at,
    updated_at,
    cancelled_at,
    closed_at
)
VALUES
    (
        (SELECT id FROM users WHERE email = 'ivan@example.com'),
        NULL,
        'PRINTER',
        'HP LaserJet Pro M404',
        'Printer does not pick up paper',
        'The printer jams every time I try to print more than one page.',
        'Started happening after replacing the toner.',
        NULL,
        NULL,
        'CREATED',
        'HIGH',
        CURRENT_TIMESTAMP - INTERVAL '2 days',
        NULL,
        NULL,
        NULL
    ),
    (
        (SELECT id FROM users WHERE email = 'olena.shevchenko@example.com'),
        (SELECT id FROM users WHERE email = 'serhii.tech@example.com'),
        'LAPTOP',
        'Dell Latitude 5520',
        'Laptop overheats during work',
        'The laptop gets very hot and shuts down after about 20 minutes.',
        'Mostly happens while using video calls.',
        'Cleaning the cooling system and checking thermal paste.',
        NULL,
        'IN_PROGRESS',
        'HIGH',
        CURRENT_TIMESTAMP - INTERVAL '1 day',
        CURRENT_TIMESTAMP - INTERVAL '3 hours',
        NULL,
        NULL
    ),
    (
        (SELECT id FROM users WHERE email = 'ivan@example.com'),
        (SELECT id FROM users WHERE email = 'svitlana.melnyk@example.com'),
        'ROUTER',
        'MikroTik hAP ac2',
        'Wi-Fi disconnects several times a day',
        'Office Wi-Fi becomes unavailable for 2-3 minutes and then reconnects.',
        'The issue is most noticeable in the afternoon.',
        'Requested additional details about the exact time of the outages.',
        NULL,
        'WAITING_FOR_USER',
        'MEDIUM',
        CURRENT_TIMESTAMP - INTERVAL '4 days',
        CURRENT_TIMESTAMP - INTERVAL '5 hours',
        NULL,
        NULL
    ),
    (
        (SELECT id FROM users WHERE email = 'olena.shevchenko@example.com'),
        (SELECT id FROM users WHERE email = 'serhii.tech@example.com'),
        'COMPUTER',
        'Lenovo ThinkCentre M720',
        'System unit does not start',
        'After pressing the power button, the computer does not boot into the operating system.',
        'Power cable and monitor were checked by the user.',
        'Replaced the failed power supply unit and tested system startup.',
        'Power supply unit replaced, BIOS settings verified, device works normally.',
        'COMPLETED',
        'MEDIUM',
        CURRENT_TIMESTAMP - INTERVAL '7 days',
        CURRENT_TIMESTAMP - INTERVAL '6 days',
        NULL,
        CURRENT_TIMESTAMP - INTERVAL '6 days'
    ),
    (
        (SELECT id FROM users WHERE email = 'ivan@example.com'),
        (SELECT id FROM users WHERE email = 'svitlana.melnyk@example.com'),
        'OTHER',
        'Document camera',
        'Image flickers during presentations',
        'The image on the projector flickers when the document camera is connected.',
        'The cable was swapped, but the problem remains.',
        'Initial inspection completed before cancellation.',
        NULL,
        'CANCELLED',
        'LOW',
        CURRENT_TIMESTAMP - INTERVAL '10 days',
        CURRENT_TIMESTAMP - INTERVAL '9 days',
        CURRENT_TIMESTAMP - INTERVAL '8 days',
        NULL
    );
