spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/maintenance_service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

app.jwt.secret=lab2-maintenance-service-jwt-secret-key-32bytes-minimum
app.jwt.expiration=86400000
